name: Test Github Actions

env:
  MOCK: mock-value

on: [label, push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js version 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      # - name: Install Dependencies
      #   run: npm ci

      - name: Set SHA as Output
        id: short_sha
        run: |
          echo ::set-output name=var::$(git rev-parse --short=7 ${{ github.sha }})
          
      - name: Set ID as Output
        id: run_id
        run: |
          echo ::set-output name=var::${{ github.run_id }}

      - name: Set SHA and ID as ENV
        run: |
          export SHORT_SHA={{ steps.short_sha.outputs.var }}
          export RUN_ID=${{ steps.run_id.outputs.var }}

      - name: Read SHA and ID from ENV
        run: |
          make test/env
