name: Test Github Actions

env:
  MOCK: mock-value

on:
  repository_dispatch:
    type: run
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.branch }}

      # - name: Use Node.js version 12.x
      #   uses: actions/setup-node@v1
      #   with:
      #     node-version: 12.x

      # - name: Install Dependencies
      #   run: npm ci
      - name: 'Get Latest tag'
        uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag

      - name: Set SHA and ID as Output
        id: var
        run: |
          echo ::set-output name=run_id::${{ github.run_id }}

      - name: Set SHA and ID as ENV
        run: |
          echo ::set-env name=SHORT_SHA::${{ env.MOCK }}-$(git log -1 --format="%h")-${{ steps.var.outputs.run_id }}.zip
          echo ::set-env name=RUN_ID::$(echo ${{ steps.var.outputs.run_id }})

      - name: Read SHA and ID from ENV
        run: make test/env

      - name: Read Latest tag
        run: echo ${{ steps.get-latest-tag.outputs.tag }}
