name: Test Github Actions

env:
  MOCK: mock-value

on: [label, push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js version 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      # - name: Install Dependencies
      #   run: npm ci

      - name: Set Github Short SHA
        id: var
        run: |
          echo ::set-output name=short_sha::$(git rev-parse --short=7 ${{ github.sha }})
          echo ::set-output name=run_id::${{ github.run_id }}

      - name: Get the Short SHA
        run: |
          echo Short SHA is ${{ steps.var.outputs.short_sha }}
          echo Run ID is ${{ steps.var.outputs.run_id }}