name: Test Github Actions

env:
  MOCK: mock-value

on: [label, push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js version 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install Dependencies
        run: npm ci

      - name: Set Github Short SHA
        id: var
        run: |
          echo ::set-output name=short_sha::$(git rev-parse --short=4 ${{ github.sha }})

      - name: Get the Short SHA
        run: |
          echo Getting this ${{ steps.var.output.short_sha }}