name: Test Github Actions

env:
  MOCK: mock-value

on: [label, push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # - name: Use Node.js version 12.x
      #   uses: actions/setup-node@v1
      #   with:
      #     node-version: 12.x

      # - name: Install Dependencies
      #   run: npm ci

      - name: Set SHA and ID as Output
        id: var
        run: |
          echo ::set-output name=short_sha::$(git rev-parse --short=7 ${{ github.sha }})
          echo ::set-output name=run_id::${{ github.run_id }}

      - name: Set SHA and ID as ENV
        run: |
          echo ::set-env name=SHORT_SHA::$(echo ${{ steps.var.outputs.short_sha }})
          echo ::set-env name=RUN_ID::$(echo ${{ steps.var.outputs.run_id }})

      - name: Read SHA and ID from ENV
        run: |
          make test/env
